### ISSUE TITLE
Segmentation fault when using qgt

### ISSUE THREAD

**Issue by mpaszkow** [johnbarton/ACE#2]
#### Description
Segmentation fault upon **qgt** execution on the p7 example ([p7-alignment.fasta](https://github.com/johnbarton/ACE/blob/6f59d055e5930021126ec8ad99d387acab05f9c0/examples/p7-alignment.fasta)). Execution breaks at the following line, most probably due to `aa[i] = 0`, giving a negative index in the `seq` vector:
https://github.com/johnbarton/ACE/blob/6f59d055e5930021126ec8ad99d387acab05f9c0/src/io.cpp#L359

#### To Reproduce
Initial correlations were generated by **WriteCMSA** from [ACEtools.py](https://github.com/johnbarton/ACE/blob/6f59d055e5930021126ec8ad99d387acab05f9c0/scripts/ACEtools.py), followed by commands from the README file:
```
$ ./bin/ace -d example_p7 -i p7 -o p7-out -g2 0.0002 -b 4130
$ ./bin/qls -d example_p7 -c p7 -i p7-out -o p7-out-learn -g2 0.0002 -b 4130
$ ./bin/qgt -d example_p7 -c p7 -m p7 -w p7 -i p7-out -o p7-out-fit -g2 0.0002 -b 4130
```

#### Files
All generated files can be extracted from the attached archive: [example_p7.tar.gz](https://github.com/johnbarton/ACE/files/3315210/example_p7.tar.gz)

**Comment by johnbarton** [comment]
Thanks very much for pointing this out @mpaszkow. It looks like the ultimate origin of this error is the difference in array numbering conventions for Matlab versus Python. I've updated the routines in ACEtools.py for generating the .cmsa files. Please let me know if this resolves the issue.

**Comment by mpaszkow** [comment]
Thank you, that was really fast! It works now.
